# Generated by Django 3.2.3 on 2021-05-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('design', models.FloatField(blank=True, default=0)),
                ('content', models.FloatField(blank=True, default=0)),
                ('usability', models.FloatField(blank=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.project')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.profile')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
