# Generated by Django 3.2.3 on 2021-06-01 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='voters',
        ),
    ]
